services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
  web:
    env_file: .env
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s  -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/sushi_app
    ports:
      - "3000:3000"
    depends_on:
      - db