services:
  db:
    env_file: .env
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: <%= ENV['POSTGRES_PASSWORD'] %>
  web:
    env_file: .env
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s  -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/sushi_app
    ports:
      - "3000:3000"
    depends_on:
      - db